import { useState, useEffect } from 'react';
import { Link, useNavigate } from 'react-router-dom';
import { Shield, Clock, ChevronRight, CheckCircle2, Wrench, Navigation, Smartphone, Lock, ShieldCheck, Award, ThumbsUp, Phone, KeyRound, Tag, Sparkles, Percent } from 'lucide-react';
import { services, initialOffers } from '../data/dummyData';
import { useAuth } from '../context/AuthContext';

const fallbackImage = "data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 800 450' width='100%25' height='100%25'%3E%3Cdefs%3E%3ClinearGradient id='bg' x1='0%25' y1='0%25' x2='100%25' y2='100%25'%3E%3Cstop offset='0%25' stop-color='%23141414'/%3E%3Cstop offset='100%25' stop-color='%23080808'/%3E%3C/linearGradient%3E%3ClinearGradient id='gold' x1='0%25' y1='0%25' x2='100%25' y2='100%25'%3E%3Cstop offset='0%25' stop-color='%23d4af37'/%3E%3Cstop offset='100%25' stop-color='%23b7791f'/%3E%3C/linearGradient%3E%3C/defs%3E%3Crect width='100%25' height='100%25' fill='url(%23bg)'/%3E%3Ccircle cx='400' cy='200' r='60' fill='%23222' stroke='url(%23gold)' stroke-width='2' opacity='0.6'/%3E%3Cpath d='M380 180 L420 220 M420 180 L380 220' stroke='url(%23gold)' stroke-width='4' stroke-linecap='round'/%3E%3Ctext x='400' y='300' font-family='sans-serif' font-size='22' font-weight='800' fill='%23d4af37' text-anchor='middle' letter-spacing='2'%3EAUTOSERVE%3C/text%3E%3Ctext x='400' y='330' font-family='sans-serif' font-size='13' fill='%23888' text-anchor='middle'%3EPREMIUM AUTOMOTIVE SERVICE%3C/text%3E%3C/svg%3E";

export default function Home() {
  const [trackInput, setTrackInput] = useState('');
  const navigate = useNavigate();
  const { isAuthenticated } = useAuth();

  // Load manager offers
  const [offers, setOffers] = useState(() => {
    try {
      const saved = localStorage.getItem('autoserve_manager_offers');
      return saved ? JSON.parse(saved) : initialOffers;
    } catch {
      return initialOffers;
    }
  });

  const handleTrack = (e) => {
    e.preventDefault();
    if (!isAuthenticated) {
      navigate('/login', { state: { from: trackInput.trim() ? `/booking/${trackInput.trim()}` : '/my-garage' } });
      return;
    }
    if (trackInput.trim()) {
      navigate(`/booking/${trackInput.trim()}`);
    }
  };

  const activeOffers = offers.filter(o => o.active !== false);

  return (
    <div className="bg-[#050505] text-white">
      {/* ─── HERO SECTION ──────────────────────────── */}
      <section 
        className="relative w-full min-h-[92vh] flex flex-col justify-center -mt-16 pt-32 pb-24 z-10"
        style={{
          backgroundImage: 'url("https://images.unsplash.com/photo-1625047509168-a7026f36de04?w=1920&h=1080&fit=crop")',
          backgroundAttachment: 'fixed',
          backgroundSize: 'cover',
          backgroundPosition: 'center'
        }}
      >
        <div className="absolute inset-0 bg-[#050505]/75 z-0" />
        <div className="absolute inset-0 bg-gradient-to-t from-[#050505] via-transparent to-transparent z-0" />

        <div className="relative z-10 max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 w-full flex flex-col lg:flex-row items-center gap-12">
          {/* Left Content */}
          <div className="w-full lg:w-1/2 animate-fade-in">
            <div className="inline-flex items-center gap-2 px-4 py-1.5 rounded-full bg-white/5 border border-white/10 backdrop-blur-md mb-6 shadow-xl">
              <span className="w-2 h-2 rounded-full bg-accent animate-ping" />
              <span className="text-xs font-bold text-accent tracking-widest uppercase">Verified Auto Care & Diagnostics</span>
            </div>
            
            <h1 className="text-4xl sm:text-5xl md:text-6xl font-extrabold text-white leading-[1.1] tracking-tight mb-6">
              Precision Servicing.<br />
              <span className="text-transparent bg-clip-text bg-gradient-to-r from-[#d4af37] via-[#f7d070] to-[#b7791f]">
                Live Stage Tracking.
              </span>
            </h1>

            <p className="text-base sm:text-lg text-gray-300 leading-relaxed mb-8 max-w-xl">
              Experience transparent, dealership-quality auto care with custom quotes generated by certified garage managers upon multi-point physical diagnostic checks.
            </p>

            {/* Action Buttons based on Auth Status */}
            <div className="flex flex-wrap items-center gap-4">
              {isAuthenticated ? (
                <Link 
                  to="/book-service" 
                  className="text-[#050505] px-8 py-4 rounded-full font-extrabold text-sm sm:text-base hover:opacity-90 transition-all active:scale-95 shadow-[0_0_25px_rgba(212,175,55,0.35)] flex items-center gap-2"
                  style={{ background: 'linear-gradient(135deg, #d4af37, #b7791f)' }}
                >
                  <Wrench size={18} /> Book a Service Now <ChevronRight size={18} />
                </Link>
              ) : (
                <Link 
                  to="/login"
                  state={{ from: '/book-service' }}
                  className="text-[#050505] px-8 py-4 rounded-full font-extrabold text-sm sm:text-base hover:opacity-90 transition-all active:scale-95 shadow-[0_0_25px_rgba(212,175,55,0.35)] flex items-center gap-2"
                  style={{ background: 'linear-gradient(135deg, #d4af37, #b7791f)' }}
                >
                  <KeyRound size={18} /> Login with Phone to Book <ChevronRight size={18} />
                </Link>
              )}

              <a 
                href="#how-it-works" 
                className="bg-white/5 text-white backdrop-blur-md border border-white/15 px-7 py-4 rounded-full font-semibold text-sm sm:text-base hover:bg-white/10 transition-all active:scale-95"
              >
                How It Works
              </a>
            </div>

            {/* Security note */}
            {!isAuthenticated && (
              <p className="text-xs text-gray-400 mt-4 flex items-center gap-1.5">
                <Lock size={13} className="text-accent" /> Phone number verification required to secure appointments and personalized quotes.
              </p>
            )}
          </div>

          {/* Right Content: Track / Overview Widget */}
          <div className="w-full lg:w-1/2 flex justify-center lg:justify-end animate-fade-in">
            <div className="glass-panel p-8 rounded-3xl w-full max-w-md shadow-2xl relative overflow-hidden border border-white/10">
              <div className="absolute top-0 right-0 w-32 h-32 bg-accent/20 blur-[60px] pointer-events-none rounded-full translate-x-1/2 -translate-y-1/2" />
              
              <div className="flex items-center gap-3 mb-4">
                <div className="w-10 h-10 rounded-xl bg-accent/20 flex items-center justify-center text-accent">
                  <Navigation size={22} />
                </div>
                <div>
                  <h3 className="text-lg font-bold text-white">Live Vehicle Tracker</h3>
                  <p className="text-xs text-gray-400">Real-time stage status from the garage bay</p>
                </div>
              </div>

              {isAuthenticated ? (
                <form onSubmit={handleTrack} className="space-y-4">
                  <p className="text-xs text-gray-300">Enter your Booking Reference ID to inspect stage progression:</p>
                  <div>
                    <input
                      type="text"
                      value={trackInput}
                      onChange={(e) => setTrackInput(e.target.value)}
                      placeholder="e.g. ASV-2026-1042"
                      className="w-full bg-white/5 border border-white/10 rounded-xl px-4 py-3 text-white text-sm outline-none focus:border-accent focus:ring-1 focus:ring-accent transition-all font-mono placeholder-gray-500"
                      required
                    />
                  </div>
                  <button
                    type="submit"
                    className="w-full bg-white text-[#050505] font-bold py-3 rounded-xl hover:bg-gray-200 transition-all active:scale-[0.98] text-sm"
                  >
                    Track Active Status
                  </button>
                </form>
              ) : (
                <div className="space-y-4">
                  <div className="p-4 rounded-2xl bg-white/5 border border-white/10 text-xs text-gray-300 leading-relaxed">
                    <span className="font-semibold text-white block mb-1">Protected Vehicle Tracking:</span>
                    For vehicle owner privacy, diagnostic quotes and live stage progression require verified phone login.
                  </div>

                  <Link
                    to="/login"
                    state={{ from: '/my-garage' }}
                    className="w-full flex items-center justify-center gap-2 py-3 px-4 rounded-xl text-[#050505] font-bold text-xs sm:text-sm transition-all shadow-md active:scale-[0.98]"
                    style={{ background: 'linear-gradient(135deg, #d4af37, #b7791f)' }}
                  >
                    <Phone size={16} /> Sign In with Phone to Track
                  </Link>
                </div>
              )}
            </div>
          </div>
        </div>

        {/* Bottom Trust Row */}
        <div className="absolute bottom-0 left-0 w-full border-t border-white/5 bg-[#050505]/70 backdrop-blur-md z-10 hidden lg:block">
          <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-4">
            <div className="flex items-center justify-between text-xs font-semibold uppercase tracking-wider text-gray-400">
              <div className="flex items-center gap-2"><ShieldCheck size={16} className="text-accent" /> Certified Master Mechanics</div>
              <div className="flex items-center gap-2"><CheckCircle2 size={16} className="text-accent" /> 100% Genuine OEM Spares</div>
              <div className="flex items-center gap-2"><Smartphone size={16} className="text-accent" /> Live WhatsApp & Web Updates</div>
              <div className="flex items-center gap-2"><Clock size={16} className="text-accent" /> Guaranteed Turnaround Time</div>
            </div>
          </div>
        </div>
      </section>

      {/* ─── LIVE MANAGER OFFERS BANNER ─────────────── */}
      {activeOffers.length > 0 && (
        <section className="py-12 bg-[#090909] border-b border-white/5 relative z-10">
          <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
            <div className="flex items-center justify-between mb-6 flex-wrap gap-2">
              <div className="flex items-center gap-2">
                <Tag size={18} className="text-accent" />
                <h3 className="text-sm sm:text-base font-bold uppercase tracking-wider text-white">Active Garage Manager Offers</h3>
              </div>
              <span className="text-xs text-gray-400">Managed in real-time by garage managers</span>
            </div>

            <div className="grid grid-cols-1 md:grid-cols-3 gap-4">
              {activeOffers.map((offer) => (
                <div key={offer.id} className="glass-card p-5 rounded-2xl border border-white/10 hover:border-accent/40 transition-all flex items-start gap-3">
                  <div className="w-10 h-10 rounded-xl bg-accent/15 border border-accent/30 text-accent font-extrabold flex items-center justify-center shrink-0">
                    <Percent size={18} />
                  </div>
                  <div className="flex-1 min-w-0">
                    <div className="flex items-center justify-between gap-1 mb-1">
                      <span className="text-xs font-bold text-white truncate">{offer.title}</span>
                      <span className="text-[10px] font-mono px-2 py-0.5 rounded-full bg-accent/20 text-accent font-bold">
                        {offer.code}
                      </span>
                    </div>
                    <p className="text-xs text-gray-400 leading-snug">{offer.description}</p>
                    <p className="text-[10px] text-accent font-bold mt-2">
                      {offer.discountType === 'percentage' ? `${offer.discountValue}% DISCOUNT` : `₹${offer.discountValue} FLAT DISCOUNT`}
                    </p>
                  </div>
                </div>
              ))}
            </div>
          </div>
        </section>
      )}

      {/* ─── HOW THE BUSINESS WORKS ─────────────────── */}
      <section className="py-24 relative overflow-hidden bg-[#070707] border-b border-white/5 z-10" id="how-it-works">
        <div className="absolute top-1/2 left-1/2 -translate-x-1/2 -translate-y-1/2 w-full h-[500px] bg-accent/5 blur-[140px] rounded-full pointer-events-none" />
        
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 relative z-10">
          <div className="text-center mb-16">
            <div className="inline-block px-3 py-1 rounded-full bg-accent/10 border border-accent/20 text-accent text-xs font-bold uppercase tracking-wider mb-3">
              Transparent Operations
            </div>
            <h2 className="text-3xl sm:text-4xl font-extrabold text-white">How AutoServe Works</h2>
            <p className="text-gray-400 text-sm max-w-2xl mx-auto mt-2">
              From phone sign-in to diagnostic assessment and drive-away, experience complete clarity with custom manager estimates and live tracking.
            </p>
          </div>
          
          <div className="grid grid-cols-1 md:grid-cols-4 gap-6">
            {[
              { 
                step: '01', 
                title: 'Phone Authentication', 
                desc: 'Sign in with your phone number to secure your vehicle profile and unlock personalized booking.', 
                icon: <Phone size={24} /> 
              },
              { 
                step: '02', 
                title: 'Select Slot & Drop-off', 
                desc: 'Pick your vehicle category, requested diagnostic scope, and reserve your priority bay slot.', 
                icon: <Clock size={24} /> 
              },
              { 
                step: '03', 
                title: 'Live 6-Stage Tracking', 
                desc: 'Watch inspecting, parts replacement, servicing, and washing update in real time.', 
                icon: <Smartphone size={24} /> 
              },
              { 
                step: '04', 
                title: 'Itemized Quote & Delivery', 
                desc: 'Review itemized parts and labor quotations with manager offers applied before pickup.', 
                icon: <CheckCircle2 size={24} /> 
              },
            ].map((item) => (
              <div key={item.step} className="glass-card p-6 rounded-3xl border border-white/10 hover:border-accent/40 transition-all duration-300 group">
                <div className="flex items-center justify-between mb-6">
                  <div className="w-12 h-12 bg-white/5 border border-white/10 rounded-2xl flex items-center justify-center text-gray-400 group-hover:text-accent group-hover:border-accent/40 transition-all">
                    {item.icon}
                  </div>
                  <span className="text-2xl font-black text-white/20 group-hover:text-accent/30 font-mono transition-colors">
                    {item.step}
                  </span>
                </div>
                <h3 className="text-base font-bold text-white mb-2 group-hover:text-accent transition-colors">{item.title}</h3>
                <p className="text-xs text-gray-400 leading-relaxed">{item.desc}</p>
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* ─── SERVICES CATALOG ───────────────────────── */}
      <section className="py-20 border-b border-white/5 bg-[#050505] relative z-10" id="services">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
          <div className="flex flex-col md:flex-row md:items-end justify-between mb-12 gap-4">
            <div>
              <div className="inline-block px-3 py-1 rounded-full bg-accent/10 border border-accent/20 text-accent text-xs font-bold uppercase tracking-wider mb-2">
                Service Catalog
              </div>
              <h2 className="text-3xl font-extrabold text-white">Our Maintenance & Diagnostic Capabilities</h2>
              <p className="text-gray-400 text-sm mt-1">Pricing and itemized quotations are customized upon physical inspection.</p>
            </div>

            {isAuthenticated ? (
              <Link to="/book-service" className="inline-flex items-center gap-1.5 text-xs font-bold text-accent hover:text-accent-light transition-colors">
                Open Booking Portal <ChevronRight size={16} />
              </Link>
            ) : (
              <Link to="/login" state={{ from: '/book-service' }} className="inline-flex items-center gap-1.5 text-xs font-bold text-accent hover:text-accent-light transition-colors">
                Sign in to Book <ChevronRight size={16} />
              </Link>
            )}
          </div>
          
          <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
            {services.map((s) => (
              <div key={s.id} className="group relative rounded-3xl overflow-hidden glass-card border border-white/10 hover:border-accent/50 transition-all duration-300">
                <div className="h-44 w-full overflow-hidden relative bg-[#111]">
                  <div className="absolute inset-0 bg-gradient-to-t from-[#0d0d0d] to-transparent z-10 pointer-events-none" />
                  <img 
                    src={s.image || fallbackImage} 
                    alt={s.name} 
                    className="w-full h-44 object-cover group-hover:scale-105 transition-transform duration-500" 
                    onError={(e) => { e.currentTarget.src = fallbackImage; }}
                  />
                  <div className="absolute top-3 right-3 z-20 px-3 py-1 rounded-full bg-[#050505]/80 backdrop-blur-md border border-white/10 text-[10px] font-bold text-accent">
                    {s.badge || 'Diagnostic Check'}
                  </div>
                </div>

                <div className="p-6 relative z-20">
                  <h3 className="text-lg font-bold text-white mb-1.5 group-hover:text-accent transition-colors">{s.name}</h3>
                  <p className="text-xs text-gray-400 mb-4 line-clamp-2 leading-relaxed">{s.description}</p>
                  
                  <div className="flex items-center justify-between pt-4 border-t border-white/10">
                    <span className="text-xs text-gray-400 flex items-center gap-1">
                      <Clock size={13} /> {s.estimatedTime}
                    </span>

                    {isAuthenticated ? (
                      <Link 
                        to="/book-service"
                        className="px-4 py-2 rounded-xl text-xs font-bold text-[#050505] transition-all hover:opacity-90 shadow-md"
                        style={{ background: 'linear-gradient(135deg, #d4af37, #b7791f)' }}
                      >
                        Book Service
                      </Link>
                    ) : (
                      <Link 
                        to="/login"
                        state={{ from: '/book-service' }}
                        className="px-4 py-2 rounded-xl text-xs font-bold text-white bg-white/10 hover:bg-white/20 border border-white/10 transition-all"
                      >
                        Login to Book
                      </Link>
                    )}
                  </div>
                </div>
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* ─── WHY CHOOSE AUTOSERVE ──────────────────── */}
      <section className="py-20 bg-[#070707] border-b border-white/5 z-10" id="about">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
          <div className="text-center mb-14">
            <h2 className="text-3xl font-extrabold text-white">Why Vehicle Owners Trust AutoServe</h2>
            <p className="text-gray-400 text-sm mt-1">Built to eliminate auto garage malpractice, delays, and fake spare parts.</p>
          </div>

          <div className="grid grid-cols-1 md:grid-cols-3 gap-6">
            <div className="glass-card p-6 rounded-3xl border border-white/10">
              <Award className="text-accent mb-4" size={32} />
              <h3 className="text-base font-bold text-white mb-2">OEM Certified Technicians</h3>
              <p className="text-xs text-gray-400 leading-relaxed">
                All repairs are carried out by vetted professionals trained on multi-brand petrol, diesel, and EV architectures.
              </p>
            </div>
            <div className="glass-card p-6 rounded-3xl border border-white/10">
              <ShieldCheck className="text-accent mb-4" size={32} />
              <h3 className="text-base font-bold text-white mb-2">1000km / 30-Day Warranty</h3>
              <p className="text-xs text-gray-400 leading-relaxed">
                Every service booked through our verified platform comes with an unconditional service warranty guarantee.
              </p>
            </div>
            <div className="glass-card p-6 rounded-3xl border border-white/10">
              <ThumbsUp className="text-accent mb-4" size={32} />
              <h3 className="text-base font-bold text-white mb-2">Zero Hidden Add-ons</h3>
              <p className="text-xs text-gray-400 leading-relaxed">
                Itemized quotes are finalized by the garage manager and approved by you on your dashboard before any work begins.
              </p>
            </div>
          </div>
        </div>
      </section>

      {/* ─── CTA BOTTOM BANNER ─────────────────────── */}
      <section className="py-20 bg-[#050505] relative z-10" id="partner">
        <div className="max-w-5xl mx-auto px-4 sm:px-6 lg:px-8">
          <div className="glass-panel relative rounded-3xl p-10 md:p-16 text-center overflow-hidden border border-white/15 shadow-2xl">
            <div className="relative z-10">
              <h2 className="text-2xl sm:text-4xl font-extrabold text-white mb-4">
                Ready to Experience Dealership-Grade Vehicle Care?
              </h2>
              <p className="text-gray-400 text-xs sm:text-sm mb-8 max-w-xl mx-auto">
                Sign in with your mobile number in seconds to unlock priority slot booking and live stage tracking.
              </p>
              
              {isAuthenticated ? (
                <Link
                  to="/book-service"
                  className="inline-flex items-center justify-center gap-2 text-[#050505] font-extrabold px-8 py-4 rounded-full hover:opacity-90 transition-all hover:scale-105 active:scale-95 text-sm shadow-[0_0_30px_rgba(212,175,55,0.4)]"
                  style={{ background: 'linear-gradient(135deg, #d4af37, #b7791f)' }}
                >
                  Schedule Your Service <ChevronRight size={16} />
                </Link>
              ) : (
                <Link
                  to="/login"
                  state={{ from: '/book-service' }}
                  className="inline-flex items-center justify-center gap-2 text-[#050505] font-extrabold px-8 py-4 rounded-full hover:opacity-90 transition-all hover:scale-105 active:scale-95 text-sm shadow-[0_0_30px_rgba(212,175,55,0.4)]"
                  style={{ background: 'linear-gradient(135deg, #d4af37, #b7791f)' }}
                >
                  <Phone size={16} /> Sign In with Phone to Book Service
                </Link>
              )}
            </div>
          </div>
        </div>
      </section>
    </div>
  );
}
